# Generated by Django 2.1.15 on 2020-01-04 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scan_ip_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('cpe', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='scanIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='scan_ip_info',
            name='ipfor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.scanIP'),
        ),
    ]
