# Generated by Django 2.1.15 on 2020-01-06 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nmapscan',
            old_name='taskid',
            new_name='task',
        ),
    ]
