# Generated by Django 2.1.15 on 2020-03-21 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auto_20200321_2302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proj_info',
            options={'permissions': (('upload_code', '可以上传代码'), ('dashboard', '首页仪表盘'))},
        ),
    ]
