# Generated by Django 2.1.15 on 2020-03-22 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auto_20200321_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proj_info',
            options={'permissions': (('upload_code', '可以上传代码'), ('display_projects', '展示所有代码审计项目'), ('display_info', '展示一个项目的详细信息'))},
        ),
    ]
