# Generated by Django 2.1.15 on 2020-03-22 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auto_20200322_0028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='setting',
        ),
        migrations.AlterModelOptions(
            name='chandao_data',
            options={'permissions': (('chandao_index', '展示禅道主页'), ('hidden_vul', '隐藏发送到禅道的漏洞'), ('filter_vul', '过滤发送到禅道的漏洞'), ('send_vul', '发送到禅道的漏洞'))},
        ),
        migrations.AlterModelOptions(
            name='proj_info',
            options={'permissions': (('upload_code_and_scan', '可以上传代码并且进行代码审计扫描'), ('restart_scan', '重新进行代码审计扫描'), ('display_projects', '展示所有代码审计项目'), ('display_info', '展示一个项目的详细信息'), ('delelte_project', '删除代码审计项目'))},
        ),
        migrations.AlterModelOptions(
            name='vul_info',
            options={'permissions': (('vullist', '返回一个项目的漏洞列表'), ('vuldetail', '返回一个项目的漏洞列表具体信息'))},
        ),
    ]
