# Generated by Django 2.1.15 on 2020-03-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='im',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('upload_code', '可以上传代码'), ('dashboard', '首页仪表盘')),
            },
        ),
    ]
