# Generated by Django 2.1.15 on 2020-03-22 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='im',
            options={'permissions': (('dashboard', '首页仪表盘'),)},
        ),
    ]
