# Generated by Django 2.0 on 2018-06-12 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chandao_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.CharField(default='', max_length=100)),
                ('vul_name', models.CharField(max_length=200)),
                ('md5', models.CharField(max_length=100)),
                ('Abstract', models.TextField()),
                ('FileName', models.CharField(max_length=50)),
                ('FilePath', models.CharField(max_length=200)),
                ('LineStart', models.CharField(max_length=10)),
                ('describe', models.TextField()),
                ('Recommendation', models.TextField()),
                ('status', models.CharField(default='0', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='chandao_person_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=10)),
                ('ename', models.CharField(max_length=100)),
                ('cname', models.CharField(max_length=200)),
                ('pid', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='proj_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('git', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.CharField(default='0', max_length=10, null=True)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('svn', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True, verbose_name='Key')),
                ('value', models.TextField(verbose_name='Value')),
            ],
        ),
        migrations.CreateModel(
            name='vul_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('risk', models.CharField(max_length=10)),
                ('Abstract', models.TextField()),
                ('FileName', models.CharField(max_length=50)),
                ('FilePath', models.CharField(max_length=200)),
                ('LineStart', models.CharField(max_length=10)),
                ('Snippet', models.TextField()),
                ('full_code', models.TextField()),
                ('extend', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now=True)),
                ('proj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aduit.proj_info')),
            ],
        ),
    ]
