# Generated by Django 2.0 on 2018-06-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aduit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proj_info',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
