# Generated by Django 2.0 on 2018-06-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aduit', '0002_proj_info_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proj_info',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
