# Generated by Django 2.0 on 2018-06-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aduit', '0003_auto_20180620_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='chandao_data',
            name='hidden',
            field=models.IntegerField(default=0),
        ),
    ]
