# Generated by Django 2.0 on 2018-06-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aduit', '0004_chandao_data_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chandao_data',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
